// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: crypto.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AESCryptoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AESCryptoRequest) Reset() {
	*x = AESCryptoRequest{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AESCryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AESCryptoRequest) ProtoMessage() {}

func (x *AESCryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AESCryptoRequest.ProtoReflect.Descriptor instead.
func (*AESCryptoRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *AESCryptoRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AESCryptoRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DESCryptoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DESCryptoRequest) Reset() {
	*x = DESCryptoRequest{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DESCryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DESCryptoRequest) ProtoMessage() {}

func (x *DESCryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DESCryptoRequest.ProtoReflect.Descriptor instead.
func (*DESCryptoRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *DESCryptoRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DESCryptoRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RSACryptoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RSACryptoRequest) Reset() {
	*x = RSACryptoRequest{}
	mi := &file_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RSACryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RSACryptoRequest) ProtoMessage() {}

func (x *RSACryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RSACryptoRequest.ProtoReflect.Descriptor instead.
func (*RSACryptoRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *RSACryptoRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RSACryptoRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RSACryptoRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *HashRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CryptoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoResponse) Reset() {
	*x = CryptoResponse{}
	mi := &file_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoResponse) ProtoMessage() {}

func (x *CryptoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoResponse.ProtoReflect.Descriptor instead.
func (*CryptoResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *CryptoResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *HashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x12\x06crypto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\"8\n" +
	"\x10AESCryptoRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"8\n" +
	"\x10DESCryptoRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"f\n" +
	"\x10RSACryptoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\"!\n" +
	"\vHashRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"(\n" +
	"\x0eCryptoResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\"\n" +
	"\fHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash2\x8c\x05\n" +
	"\rCryptoService\x12Z\n" +
	"\n" +
	"EncryptAES\x12\x18.crypto.AESCryptoRequest\x1a\x16.crypto.CryptoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/encrypt/aes\x12Z\n" +
	"\n" +
	"DecryptAES\x12\x18.crypto.AESCryptoRequest\x1a\x16.crypto.CryptoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/decrypt/aes\x12Z\n" +
	"\n" +
	"EncryptDES\x12\x18.crypto.DESCryptoRequest\x1a\x16.crypto.CryptoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/encrypt/des\x12Z\n" +
	"\n" +
	"DecryptDES\x12\x18.crypto.DESCryptoRequest\x1a\x16.crypto.CryptoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/decrypt/des\x12Z\n" +
	"\n" +
	"EncryptRSA\x12\x18.crypto.RSACryptoRequest\x1a\x16.crypto.CryptoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/encrypt/rsa\x12Z\n" +
	"\n" +
	"DecryptRSA\x12\x18.crypto.RSACryptoRequest\x1a\x16.crypto.CryptoResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/decrypt/rsa\x12S\n" +
	"\n" +
	"HashSHA256\x12\x13.crypto.HashRequest\x1a\x14.crypto.HashResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/hash/sha256B\x19Z\x17grpc-crypto/proto;protob\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_crypto_proto_goTypes = []any{
	(*AESCryptoRequest)(nil), // 0: crypto.AESCryptoRequest
	(*DESCryptoRequest)(nil), // 1: crypto.DESCryptoRequest
	(*RSACryptoRequest)(nil), // 2: crypto.RSACryptoRequest
	(*HashRequest)(nil),      // 3: crypto.HashRequest
	(*CryptoResponse)(nil),   // 4: crypto.CryptoResponse
	(*HashResponse)(nil),     // 5: crypto.HashResponse
}
var file_crypto_proto_depIdxs = []int32{
	0, // 0: crypto.CryptoService.EncryptAES:input_type -> crypto.AESCryptoRequest
	0, // 1: crypto.CryptoService.DecryptAES:input_type -> crypto.AESCryptoRequest
	1, // 2: crypto.CryptoService.EncryptDES:input_type -> crypto.DESCryptoRequest
	1, // 3: crypto.CryptoService.DecryptDES:input_type -> crypto.DESCryptoRequest
	2, // 4: crypto.CryptoService.EncryptRSA:input_type -> crypto.RSACryptoRequest
	2, // 5: crypto.CryptoService.DecryptRSA:input_type -> crypto.RSACryptoRequest
	3, // 6: crypto.CryptoService.HashSHA256:input_type -> crypto.HashRequest
	4, // 7: crypto.CryptoService.EncryptAES:output_type -> crypto.CryptoResponse
	4, // 8: crypto.CryptoService.DecryptAES:output_type -> crypto.CryptoResponse
	4, // 9: crypto.CryptoService.EncryptDES:output_type -> crypto.CryptoResponse
	4, // 10: crypto.CryptoService.DecryptDES:output_type -> crypto.CryptoResponse
	4, // 11: crypto.CryptoService.EncryptRSA:output_type -> crypto.CryptoResponse
	4, // 12: crypto.CryptoService.DecryptRSA:output_type -> crypto.CryptoResponse
	5, // 13: crypto.CryptoService.HashSHA256:output_type -> crypto.HashResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
