// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: crypto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptoService_EncryptAES_FullMethodName = "/crypto.CryptoService/EncryptAES"
	CryptoService_DecryptAES_FullMethodName = "/crypto.CryptoService/DecryptAES"
	CryptoService_EncryptDES_FullMethodName = "/crypto.CryptoService/EncryptDES"
	CryptoService_DecryptDES_FullMethodName = "/crypto.CryptoService/DecryptDES"
	CryptoService_EncryptRSA_FullMethodName = "/crypto.CryptoService/EncryptRSA"
	CryptoService_DecryptRSA_FullMethodName = "/crypto.CryptoService/DecryptRSA"
	CryptoService_HashSHA256_FullMethodName = "/crypto.CryptoService/HashSHA256"
)

// CryptoServiceClient is the client API for CryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptoServiceClient interface {
	EncryptAES(ctx context.Context, in *AESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	DecryptAES(ctx context.Context, in *AESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	EncryptDES(ctx context.Context, in *DESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	DecryptDES(ctx context.Context, in *DESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	EncryptRSA(ctx context.Context, in *RSACryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	DecryptRSA(ctx context.Context, in *RSACryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error)
	HashSHA256(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
}

type cryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptoServiceClient(cc grpc.ClientConnInterface) CryptoServiceClient {
	return &cryptoServiceClient{cc}
}

func (c *cryptoServiceClient) EncryptAES(ctx context.Context, in *AESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, CryptoService_EncryptAES_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) DecryptAES(ctx context.Context, in *AESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, CryptoService_DecryptAES_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) EncryptDES(ctx context.Context, in *DESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, CryptoService_EncryptDES_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) DecryptDES(ctx context.Context, in *DESCryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, CryptoService_DecryptDES_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) EncryptRSA(ctx context.Context, in *RSACryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, CryptoService_EncryptRSA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) DecryptRSA(ctx context.Context, in *RSACryptoRequest, opts ...grpc.CallOption) (*CryptoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CryptoResponse)
	err := c.cc.Invoke(ctx, CryptoService_DecryptRSA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptoServiceClient) HashSHA256(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, CryptoService_HashSHA256_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptoServiceServer is the server API for CryptoService service.
// All implementations must embed UnimplementedCryptoServiceServer
// for forward compatibility.
type CryptoServiceServer interface {
	EncryptAES(context.Context, *AESCryptoRequest) (*CryptoResponse, error)
	DecryptAES(context.Context, *AESCryptoRequest) (*CryptoResponse, error)
	EncryptDES(context.Context, *DESCryptoRequest) (*CryptoResponse, error)
	DecryptDES(context.Context, *DESCryptoRequest) (*CryptoResponse, error)
	EncryptRSA(context.Context, *RSACryptoRequest) (*CryptoResponse, error)
	DecryptRSA(context.Context, *RSACryptoRequest) (*CryptoResponse, error)
	HashSHA256(context.Context, *HashRequest) (*HashResponse, error)
	mustEmbedUnimplementedCryptoServiceServer()
}

// UnimplementedCryptoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptoServiceServer struct{}

func (UnimplementedCryptoServiceServer) EncryptAES(context.Context, *AESCryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptAES not implemented")
}
func (UnimplementedCryptoServiceServer) DecryptAES(context.Context, *AESCryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptAES not implemented")
}
func (UnimplementedCryptoServiceServer) EncryptDES(context.Context, *DESCryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptDES not implemented")
}
func (UnimplementedCryptoServiceServer) DecryptDES(context.Context, *DESCryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptDES not implemented")
}
func (UnimplementedCryptoServiceServer) EncryptRSA(context.Context, *RSACryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptRSA not implemented")
}
func (UnimplementedCryptoServiceServer) DecryptRSA(context.Context, *RSACryptoRequest) (*CryptoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecryptRSA not implemented")
}
func (UnimplementedCryptoServiceServer) HashSHA256(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HashSHA256 not implemented")
}
func (UnimplementedCryptoServiceServer) mustEmbedUnimplementedCryptoServiceServer() {}
func (UnimplementedCryptoServiceServer) testEmbeddedByValue()                       {}

// UnsafeCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptoServiceServer will
// result in compilation errors.
type UnsafeCryptoServiceServer interface {
	mustEmbedUnimplementedCryptoServiceServer()
}

func RegisterCryptoServiceServer(s grpc.ServiceRegistrar, srv CryptoServiceServer) {
	// If the following call pancis, it indicates UnimplementedCryptoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptoService_ServiceDesc, srv)
}

func _CryptoService_EncryptAES_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AESCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).EncryptAES(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_EncryptAES_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).EncryptAES(ctx, req.(*AESCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_DecryptAES_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AESCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).DecryptAES(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_DecryptAES_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).DecryptAES(ctx, req.(*AESCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_EncryptDES_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DESCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).EncryptDES(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_EncryptDES_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).EncryptDES(ctx, req.(*DESCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_DecryptDES_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DESCryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).DecryptDES(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_DecryptDES_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).DecryptDES(ctx, req.(*DESCryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_EncryptRSA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSACryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).EncryptRSA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_EncryptRSA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).EncryptRSA(ctx, req.(*RSACryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_DecryptRSA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RSACryptoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).DecryptRSA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_DecryptRSA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).DecryptRSA(ctx, req.(*RSACryptoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CryptoService_HashSHA256_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptoServiceServer).HashSHA256(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptoService_HashSHA256_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptoServiceServer).HashSHA256(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptoService_ServiceDesc is the grpc.ServiceDesc for CryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crypto.CryptoService",
	HandlerType: (*CryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EncryptAES",
			Handler:    _CryptoService_EncryptAES_Handler,
		},
		{
			MethodName: "DecryptAES",
			Handler:    _CryptoService_DecryptAES_Handler,
		},
		{
			MethodName: "EncryptDES",
			Handler:    _CryptoService_EncryptDES_Handler,
		},
		{
			MethodName: "DecryptDES",
			Handler:    _CryptoService_DecryptDES_Handler,
		},
		{
			MethodName: "EncryptRSA",
			Handler:    _CryptoService_EncryptRSA_Handler,
		},
		{
			MethodName: "DecryptRSA",
			Handler:    _CryptoService_DecryptRSA_Handler,
		},
		{
			MethodName: "HashSHA256",
			Handler:    _CryptoService_HashSHA256_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crypto.proto",
}
